/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micro;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //a method that takes in a string
    // return a boolean if a palendrone
    // 131 true
    // 123 false
    // adA false

    public static boolean pal(String input) throws IllegalArgumentException {
        if(input == null || input.length() < 1){
            throw new IllegalArgumentException("No empty Strings or nulls allowed");
        }

        for(int i = 0; i < input.length() / 2; i++){
            // if to check front and rear
            char frontChar = input.charAt(i);
            char lastChar = input.charAt((input.length() - 1) - i);

            if(frontChar != lastChar){
                return false;
            }
        }

        return true;

    }

    // could be a palindrone?
    // returning inforamtion as you go
    // aabbaa -> 4a2b
    // aabba -> 3a2b
    // a-a-b-b-a-a store the letter as the key in a hashtable
    // store the count as the value

    // next steps; work from home. So stuff is weird, CAD test and another coding test
    // a couple days, some time this week

}
